includes:
- ../configs/captioning/m4c_textcaps/butd_beam_search.yml
dataset_attributes:
  coco:
    processors:
      text_processor:
        params:
          vocab:
            vocab_file: vocabs/vocabulary_captioning_thresh5.txt
      caption_processor:
        params:
          vocab:
            vocab_file: vocabs/vocabulary_captioning_thresh5.txt
